# 🎙️ Keerthana Gummuluri Venkata — Audio Analyst
## Multimodal Crime / Incident Report Analyzer

**Data Type:** Emergency audio calls / witness voice statements  
**Objective:** Convert audio → text → structured CSV with event, location, sentiment, urgency

### Pipeline:
1. Load audio files
2. Transcribe with OpenAI Whisper
3. Extract keywords & entities with spaCy
4. Sentiment/urgency analysis with HuggingFace
5. Output structured CSV

In [1]:
# =============================================
# CELL 1: Install Dependencies
# =============================================
!pip install -q openai-whisper spacy transformers torch torchaudio pandas
!python -m spacy download en_core_web_sm

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 803.2/803.2 kB 9.9 MB/s eta 0:00:0000:0100:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.3/188.3 MB 9.2 MB/s eta 0:00:00:00:0100:01
  Building wheel for openai-whisper (pyproject.toml) ... done
Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 53.5 MB/s eta 0:00:0000:010:01
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [2]:
# =============================================
# CELL 2: Import Libraries
# =============================================
import whisper
import spacy
import pandas as pd
import torch
import os
import warnings
warnings.filterwarnings('ignore')

from transformers import pipeline

# Load models
print("Loading Whisper model...")
whisper_model = whisper.load_model("base")  # Use 'small' or 'medium' for better accuracy

print("Loading spaCy NER model...")
nlp = spacy.load("en_core_web_sm")

print("Loading sentiment analysis pipeline...")
sentiment_analyzer = pipeline("sentiment-analysis", model="distilbert-base-uncased-finetuned-sst-2-english")

print("All models loaded!")

Loading Whisper model...

100%|████████████████████████████████████████| 139M/139M [00:00<00:00, 149MiB/s]

Loading spaCy NER model...
Loading sentiment analysis pipeline...

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

All models loaded!

### Dataset: 911 Recordings — The First 6 Seconds

In [3]:
# =============================================
# CELL 3: Load 911 Audio Dataset
# =============================================
import os, glob

audio_dir = "/kaggle/input/datasets/louisteitelbaum/911-recordings-first-6-seconds"
all_audio_files = sorted(glob.glob(os.path.join(audio_dir, "**", "*.wav"), recursive=True))

print(f"Total audio files: {len(all_audio_files)}")
for f in all_audio_files[:5]:
    print(f"  {os.path.basename(f)} — {os.path.getsize(f):,} bytes")
if len(all_audio_files) > 5:
    print(f"  ... and {len(all_audio_files) - 5} more")

Total audio files: 707
  call_100_0.wav — 1,058,444 bytes
  call_101_0.wav — 1,058,444 bytes
  call_102_0.wav — 529,244 bytes
  call_103_0.wav — 1,058,444 bytes
  call_104_0.wav — 1,152,044 bytes
  ... and 702 more

In [4]:
# =============================================
# CELL 4: Transcription with Whisper
# =============================================

def transcribe_audio(file_path):
    """Transcribe audio file using OpenAI Whisper."""
    try:
        result = whisper_model.transcribe(file_path)
        return result["text"].strip()
    except Exception as e:
        print(f"Error transcribing {file_path}: {e}")
        return ""

# Transcribe all audio files from the Kaggle dataset
# Limit to first N files for speed (increase for full run)

files_to_process = all_audio_files

print(f"Transcribing {len(files_to_process)} / {len(all_audio_files)} audio files with Whisper...")
print("(Increase MAX_FILES above to process more)\n")

transcriptions = []
for i, filepath in enumerate(files_to_process, 1):
    filename = os.path.basename(filepath)
    print(f"  [{i}/{len(files_to_process)}] {filename}...", end=" ")

    transcript = transcribe_audio(filepath)
    call_id = f"C{i:03d}"

    transcriptions.append({
        "Call_ID": call_id,
        "Filename": filename,
        "Transcript": transcript
    })
    preview = transcript[:60] + "..." if len(transcript) > 60 else transcript
    print(f"Done: {preview}" if transcript else "No speech detected")

df_transcripts = pd.DataFrame(transcriptions)

# Remove rows with empty transcripts
empty_count = (df_transcripts["Transcript"] == "").sum()
if empty_count > 0:
    print(f"\nRemoving {empty_count} files with no detected speech.")
    df_transcripts = df_transcripts[df_transcripts["Transcript"] != ""].reset_index(drop=True)

print(f"\nSuccessfully transcribed: {len(df_transcripts)} audio files.")
df_transcripts.head(10)

Transcribing 707 / 707 audio files with Whisper...
(Increase MAX_FILES above to process more)

  [1/707] call_100_0.wav... Done: one different
  [2/707] call_101_0.wav... Done: This is the Blocopia Bank in 1302 with the Transnational Spe...
  [3/707] call_102_0.wav... Done: Yeah? Yeah. Yeah. Yeah. Yeah. Yeah.
  [4/707] call_103_0.wav... Done: Yes, we're at the Nelson building and there's some men here ...
  [5/707] call_104_0.wav... Done: Listen, we're playing really bad at this. Okay, so get on ou...
  [6/707] call_104_1.wav... Done: ...
  [7/707] call_105_0.wav... Done: I'm locking in the field and I'm looking for a champ. You're...
  [8/707] call_106_0.wav... Done: Marg massacre deBen
  [9/707] call_106_1.wav... Done: They'll remember to come out, and the others figured they're...
  [10/707] call_106_2.wav... Done: Okay, it's out for the study. Down there in the hall. We'll ...
  [11/707] call_106_3.wav... Done: Yes, that's two sub-pro here that's the 8 on the ground. Oka...
  [12/707] call_107_0.wav... Done: I mean, I'll wait behind the... ...and the fighters won't tu...
  [13/707] call_108_0.wav... Done: I'm here at the police station. I'm going to hold. Okay.
  [14/707] call_109_0.wav... Done: Yes, ma'am, I need to go out and leave quickly. Down the chu...
  [15/707] call_10_0.wav... Done: Ma'am, my cat is a person. I had to go find it.
  [16/707] call_110_0.wav... Done: Hello? Hello? Hello? Hello? Oh, that one was...
  [17/707] call_111_0.wav... Done: I'm across 4709, 40th Avenue. And to your point, our Energy ...
  [18/707] call_112_0.wav... Done: I need somebody escorted out of my store right away. He's ca...
  [19/707] call_114_0.wav... Done: Hello! Hello! Hello 911!
  [20/707] call_115_0.wav... Done: I got three people, the second people, thank you. They're ta...
  [21/707] call_116_0.wav... Done: Hey, um, they just woke into my house. They had guns. They t...
  [22/707] call_117_0.wav... Done: Um, I took some pills and um, the pills were really good mad...
  [23/707] call_118_0.wav... Done: All right, well, the thing is, I was just flying with my bud...
  [24/707] call_119_0.wav... Done: If somebody stays with Diane, I'm home alone and he's not he...
  [25/707] call_11_0.wav... Done: I don't have an emergency tube for this stuff, it just left ...
  [26/707] call_122_0.wav... Done: My house is on fire. I don't know how to sleep in and I'll g...
  [27/707] call_123_0.wav... Done: Hi, my name is Maria. I'm calling because my teacher, Mr. Ha...
  [28/707] call_124_0.wav... Done: Yes, I have a gun and I don't it's from LA car loaded and so...
  [29/707] call_125_0.wav... Done: I have a friend who's been drinking, I've been trying to hel...
  [30/707] call_126_0.wav... Done: I'm a police at where the heck am I? 291 water counts, three...
  [31/707] call_127_0.wav... Done: I'm not sure my friend is called and basically told me she w...
  [32/707] call_127_1.wav... Done: with the address, 750 south to 50 west.
  [33/707] call_127_2.wav... Done: emergency. Fire. Cutting wood. So, what's the location?
  [34/707] call_129_0.wav... Done: It's not my, I mean, I haven't made it, I haven't possible, ...
  [35/707] call_12_0.wav... Done: Turn right here, then. Man...
  [36/707] call_130_0.wav... Done: Yeah man, I'm a bit late today and we're in the road. We're ...
  [37/707] call_131_0.wav... Done: and hoping for 29 and 2 with forces and I just ran a call ju...
  [38/707] call_132_0.wav... Done: Now, I won't let you know that I'm sleepy. But I heard my do...
  [39/707] call_133_0.wav... Done: Please come down here. What's your, what? I don't know that ...
  [40/707] call_134_0.wav... Done: What was your weekend of a playboy end down a month in park?...
  [41/707] call_135_0.wav... Done: Oh, somebody is coming. Somebody help. What's going on?
  [42/707] call_136_0.wav... Done: Somebody was trying to rob us. She got tight right now. We'r...
  [43/707] call_137_0.wav... Done: Hello? Hello, I'm floating down the river in my car. Okay, w...
  [44/707] call_138_0.wav... Done: Yes, I need an ambulance on hard stones. Okay, we're in the ...
  [45/707] call_139_0.wav... Done: with that little boy missing. Have you had any reports on on...
  [46/707] call_13_0.wav... Done: We need police. Let's find a bike by 5.23. Let's find on the...
  [47/707] call_140_0.wav... Done: man please help me I'm a county road 900 to 600 will build t...
  [48/707] call_141_0.wav... Done: I'm working to please my, I'm with you right here at America...
  [49/707] call_142_0.wav... Done: I'm not a prospect but I need to have somebody go to my brot...
  [50/707] call_144_0.wav... Done: one one. Hey, my friend is having a feature. Where are you a...
  [51/707] call_145_0.wav... Done: Hello? Yes. We've just been robbed. Where? 220,000.
  [52/707] call_146_0.wav... Done: High Springs Community School, I called 911 a few minutes ag...
  [53/707] call_147_0.wav... Done: Yeah, I need an ambulance to 12 mark in South Reno. Okay, le...
  [54/707] call_148_0.wav... Done: We, they have just whom to call until you a The ledger
  [55/707] call_152_0.wav... Done: 4980. I'm talking to my daughter right now. 4980. I'm talkin...
  [56/707] call_153_0.wav... Done: It's been a demolishing of a house and there is a woman insi...
  [57/707] call_154_0.wav... Done: to help you. Hi, this is Latisha from store Big Five on Gree...
  [58/707] call_155_0.wav... Done: Yes, ma'am, my neighbor just ran over so someone tried to ki...
  [59/707] call_156_0.wav... Done: 911. My dad has been physically and emotionally assuming me ...
  [60/707] call_157_0.wav... Done: Yeah, I've got kind of like a knife. My father don't leave a...
  [61/707] call_157_1.wav... Done: My husband is up in the attic and he's not responding.
  [62/707] call_158_0.wav... Done: I need to report a murder. Okay, where is that? 157 red-
  [63/707] call_159_0.wav... Done: Yeah, it's very much right there in the back. I just think I...
  [64/707] call_15_0.wav... Done: I'm Joan Pearson and I just killed two people.
  [65/707] call_160_0.wav... Done: Hey, I told you some rally. We've got a medical aburge that ...
  [66/707] call_162_0.wav... Done: I just got back from work. From Target. I'm at 330.
  [67/707] call_163_0.wav... Done: Yes, we need an ambulance. We're at Westport Shopping Center...
  [68/707] call_164_0.wav... Done: No, I won't! I won't! I won't!
  [69/707] call_165_0.wav... Done: Yes, excuse me, so some helicopter is came down. The helicop...
  [70/707] call_165_1.wav... Done: Yes, helicopter just crashed. A helicopter just crashed? Yes...
  [71/707] call_167_0.wav... Done: Good enough, Avenue. Someone is running around the neighborh...
  [72/707] call_168_0.wav... Done: Hey, who's it? Sheriff's office can I help you? Yeah, who's ...
  [73/707] call_169_0.wav... Done: of your emergency. A month has spoken to my house and my tim...
  [74/707] call_16_0.wav... Done: Do I need any of them to please after or won't? Okay, you ne...
  [75/707] call_170_0.wav... Done: Oh my God, I'm on third Avenue to wherever I'll track somebo...
  [76/707] call_171_0.wav... Done: I hopped, there's a sitting on arm, yeah, like we're sitting...
  [77/707] call_172_0.wav... Done: of the
  [78/707] call_173_0.wav... Done: I have just smothered my way.
  [79/707] call_174_0.wav... Done: We're on the boat right now. My friend says, got it by the s...
  [80/707] call_175_0.wav... Done: Yes, I got I just shot someone in my business on that 59 31
  [81/707] call_176_0.wav... Done: We got some shootings over here in Silbeach. Okay, where? Th...
  [82/707] call_177_0.wav... Done: I just killed someone, a hundred, about 40.
  [83/707] call_178_0.wav... Done: Okay, yes, Emily, Katie, and the traffic search. She's in th...
  [84/707] call_179_0.wav... Done: I got a report of shooting. Okay, where? Lehigh Hansen for M...
  [85/707] call_179_1.wav... Done: We need the police here. Okay, what's the address of the eme...
  [86/707] call_17_0.wav... Done: Okay, we've got a fire down here at the Route 7 right here a...
  [87/707] call_180_0.wav... Done: I want to tell you what's happening first. I just killed my ...
  [88/707] call_181_0.wav... Done: What do we say? What happened? I'm sorry, I'm sorry. I'm sor...
  [89/707] call_182_0.wav... Done: We have been shot at a house in South Mim2. We have three ch...
  [90/707] call_183_0.wav... Done: Sorry I Did come to
  [91/707] call_184_0.wav... Done: I'm behind the Noseville for Vata, license plate, CEG 8148, ...
  [92/707] call_185_0.wav... Done: 4202 Mallor circle. Two men have just crossed my fence to tr...
  [93/707] call_186_0.wav... Done: What city are you in?
  [94/707] call_187_0.wav... Done: I am going eastbound on I-10 between LA-30 and LA-44.
  [95/707] call_188_0.wav... Done: Yes, we need officer right now. There's a man shooting at th...
  [96/707] call_189_0.wav... Done: for constant but continuously and at the beginning, that is,
  [97/707] call_18_0.wav... Done: your meditation. I am a little boy having a new name. Let me...
  [98/707] call_190_0.wav... Done: Okay, I call before and I already pay in back. All right, so...
  [99/707] call_191_0.wav... Done: Yeah, I'm putting myself in for my husband, the number.
  [100/707] call_192_0.wav... Done: I'm someone's breaking into my house. Wish I'd grab. Sophie,...
  [101/707] call_193_0.wav... Done: I know. I'm sorry, Gordon. I know when she shot me with... I...
  [102/707] call_194_0.wav... Done: Yes, sir. I've got this middle school. We have a student wit...
  [103/707] call_195_0.wav... Done: I'm not sure if I'm going to get by train. Why was you hit b...
  [104/707] call_196_0.wav... Done: an ambulance to the south side Walmart immediately. What's g...
  [105/707] call_197_0.wav... Done: and you child. You shot some.
  [106/707] call_198_0.wav... Done: I'm hoping. I'll leave in the lab, I think someone is trying...
  [107/707] call_199_0.wav... Done: I need a nice grey billed place, I don't care who's 15612.
  [108/707] call_19_0.wav... Done: I don't know but you have 4,000
  [109/707] call_200_0.wav... Done: We have a I think we have a dead person in here. Okay. I don...
  [110/707] call_201_0.wav... Done: I'm almost in Wonder Rock, the US bank, and I just need to b...
  [111/707] call_203_0.wav... Done: What are you? The emergency hotline. Who are you?
  [112/707] call_204_0.wav... Done: It's a business. I believe it's been robbed. What's the name...
  [113/707] call_205_0.wav... Done: and what is your emergency? Hi, my name is Mickey. I'm the m...
  [114/707] call_206_0.wav... Done: I think we're on 75. I 75? Yes. Okay.
  [115/707] call_208_0.wav... Done: Something is going on. Do you know the south number?
  [116/707] call_209_0.wav... Done: I keep blow-drow. We have blitz. Okay, I'm sorry you have bl...
  [117/707] call_20_0.wav... Done: Are you out of the house yet? No. Or I get out of the house....
  [118/707] call_210_0.wav... Done: emergency. My focus is on that please come. We're going to s...
  [119/707] call_211_0.wav... Done: Oh, darling, he's ill. Who is this? I told my father right t...
  [120/707] call_212_0.wav... Done: everyone
  [121/707] call_213_0.wav... Done: Um, we have somebody. Sorry.
  [122/707] call_214_0.wav... Done: I think somebody is breaking in the house. We just came from...
  [123/707] call_215_0.wav... Done: Um, I always offers, kind of, my mom's on a floor.
  [124/707] call_216_0.wav... Done: emergency. I just shot my wife. Can you tell me the address ...
  [125/707] call_217_0.wav... Done: I think we need a place at the Walmart Super Center in Miss ...
  [126/707] call_218_0.wav... Done: Yeah, I need the Polo here. 963, he's 363. There's somebody ...
  [127/707] call_219_0.wav... Done: corner of 119 and counting road 1 we just saw plane go down ...
  [128/707] call_219_1.wav... Done: A plane just crashed. Okay, you said three miles south of Un...
  [129/707] call_21_0.wav... Done: Yes, it is a police station. Yes, it is. May I help you? Yes...
  [130/707] call_220_0.wav... Done: I know there's an ambulance on the TV for this little boy. O...
  [131/707] call_221_0.wav... Done: Hi, we just witnessed the vehicle accident on the So you
  [132/707] call_221_1.wav... Done: There's a horrible accident on 7 mile fare in highway 94.
  [133/707] call_221_2.wav... Done: Hi, there was a accident. We just witnessed three cars just ...
  [134/707] call_222_0.wav... Done: I was told to call my dad to tell whatever I had.
  [135/707] call_223_0.wav... Done: He only found his dad's old proofs best, but I don't know.
  [136/707] call_224_0.wav... Done: Hello.
  [137/707] call_225_0.wav... Done: There has been a murder suicide. There is no survivors. Plea...
  [138/707] call_228_0.wav... Done: यह पलीज वारा हैं वार वार वार वार वार वार वार
  [139/707] call_229_0.wav... Done: Yeah, I'd like to report it to you, please. Okay. Be the thr...
  [140/707] call_230_0.wav... Done: I just shot my wife. Okay, and what's your address?
  [141/707] call_231_0.wav... Done: Please come out of the cow! Please! It's coming to God! Plea...
  [142/707] call_232_0.wav... Done: A woman came under her house screaming that her son had shot...
  [143/707] call_233_0.wav... Done: Hi, I hear a girlfriend just pulled up and there's a guy pul...
  [144/707] call_234_0.wav... Done: Hi, Edons, Unshots. We're all on the floor. You're doing wha...
  [145/707] call_235_0.wav... Done: I'm not talking about this. I'm talking about this. I'm talk...
  [146/707] call_236_0.wav... Done: Someone with murder, I think. Where are you? No, please, you...
  [147/707] call_237_0.wav... Done: It was guys just in my mom and my niece and my sister all th...
  [148/707] call_238_0.wav... Done: I have a gun shop victim here. Okay, I'm going to hurry.
  [149/707] call_240_0.wav... Done: I just come in to pick it up my trash and my major is in the...
  [150/707] call_241_0.wav... Done: Доляuria, б corporальный
  [151/707] call_242_0.wav... Done: You need to see this ran over and they said that the boy jus...
  [152/707] call_243_0.wav... Done: I requested a state police to come out. I would like state p...
  [153/707] call_244_0.wav... Done: I had a guy kicking in my door or trying to kick in my front...
  [154/707] call_245_0.wav... Done: in 59 to capture races. There's been a shooting. Somebody ca...
  [155/707] call_246_0.wav... Done: exit of this game coming from the beach. There's a guy that'...
  [156/707] call_246_1.wav... Done: There's a naked man or the men's cars way at the end of the ...
  [157/707] call_247_0.wav... Done: So hi I'm Erie C. I'm Erie C. I'm my great-for-delie.
  [158/707] call_248_0.wav... Done: I have a boy that was underwater and he's not breathing. How...
  [159/707] call_249_0.wav... Done: Are you inside the house? Yes. Are you alone inside the hous...
  [160/707] call_250_0.wav... Done: someone on the back porch of black man. And what is your add...
  [161/707] call_251_0.wav... Done: I'm gonna take a look at how I put it. How the power of this...
  [162/707] call_252_0.wav... Done: I'm going to come and stop. Where are you at? I'm at the end...
  [163/707] call_253_0.wav... Done: What kind of appearance is that? Your wet? What kind of appe...
  [164/707] call_254_0.wav... Done: We had several police tire earlier and did a report.
  [165/707] call_255_0.wav... Done: Oh, right, brother. It's having a great time in the hotel. O...
  [166/707] call_256_0.wav... Done: I just strangled my girlfriend. You just strangled your girl...
  [167/707] call_257_0.wav... Done: Okay, we've had an airboat accident. I'm not sure if they're...
  [168/707] call_258_0.wav... Done: Hey, I see a mead down
  [169/707] call_261_0.wav... Done: a subtle phenomena. Did I hear any variable?
  [170/707] call_262_0.wav... Done: I'm going to go now. I'll be right there. Do you have a hand...
  [171/707] call_263_0.wav... Done: Gute Menschen aus dem Grund routieren,ome researchers von de...
  [172/707] call_263_1.wav... Done: I was just going to six temple and there was a I was in the ...
  [173/707] call_264_0.wav... Done: Yes, somebody just send my baby please get here. They just d...
  [174/707] call_265_0.wav... Done: Oh, there's a fucking dead man in the car. Roger for me, you...
  [175/707] call_266_0.wav... Done: Can I help you? Somebody who's broken our daughter's trying ...
  [176/707] call_267_0.wav... Done: Please, before I get through, I have my shirt in here. The s...
  [177/707] call_268_0.wav... Done: Please fire. 9-1-1. My hands will be having a harder time. B...
  [178/707] call_269_0.wav... Done: you. I'll do you off with the shots. With what agency sir?
  [179/707] call_271_0.wav... Done: I just killed my mom and my sister. What? I just killed my m...
  [180/707] call_272_0.wav... Done: How come because I'm at a port in my side and this is it? Wh...
  [181/707] call_274_0.wav... Done: We have two boards, two boards. Do you have lights to servic...
  [182/707] call_275_0.wav... Done: It's been with gardens and sin as possible to the ladies. It...
  [183/707] call_276_0.wav... Done: I just committed a father's worst sin. Okay. I just shot my ...
  [184/707] call_277_0.wav... Done: Yes, I have a three year old who's not breathing. To address...
  [185/707] call_278_0.wav... Done: I have an emergency. I have three dead people up on top. It'...
  [186/707] call_279_0.wav... Done: Who's finished shooting? Okay, who was shot?
  [187/707] call_27_0.wav... Done: N5631, Sahel Road.
  [188/707] call_280_0.wav... Done: Um, I don't know a guy stopped me. I think his wife is stron...
  [189/707] call_282_0.wav... Done: We need help my husband to shop my son
  [190/707] call_283_0.wav... Done: Place, this is Dale Ford, Passdresser, 217th. I'm called a b...
  [191/707] call_284_0.wav... Done: Come on in your side, busing up vehicle man. I don't know wh...
  [192/707] call_286_0.wav... Done: have you got any reports of a building exposure? Yes we have...
  [193/707] call_286_1.wav... Done: I looked at the money, get the order, buy themagda, think I ...
  [194/707] call_286_2.wav... Done: We just have the explosion at the front of our door. Yes sir...
  [195/707] call_286_3.wav... Done: Gary Masek-Grab, all the house blew up. Now's the windshield...
  [196/707] call_286_4.wav... Done: Yes, where West Texas, the firstравlaveryink, was born up an...
  [197/707] call_286_5.wav... Done: Yes, the 1000 exploded. Okay, what's the end like? 1879.
  [198/707] call_287_0.wav... Done: Oh, dude, the guy with the Josh suit is a new world ball rig...
  [199/707] call_289_0.wav... Done: I'm a name of Hans Walters. I work for a lot of Vegas, much ...
  [200/707] call_28_0.wav... Done: Can you please send rescue to I think I'm having
  [201/707] call_290_0.wav... Done: I'm out of South High School. There's everything underground...
  [202/707] call_291_0.wav... Done: You need police fire ambulance.
  [203/707] call_292_0.wav... Done: We have a shooter in the store. Okay, do you know if anybody...
  [204/707] call_292_1.wav... Done: Okay. Okay. I need to get your stuff to a safe location.
  [205/707] call_292_2.wav... Done: emergency. We're out of the town center.
  [206/707] call_292_3.wav... Done: 911. Clackerman's town center, Frederick's of Hollywood, fir...
  [207/707] call_293_0.wav... Done: Hi, I'm a suicidal teenager at House 503 Nighthawk Drive. I ...
  [208/707] call_294_0.wav... Done: 500 feet, roll the cop, roll an ambulance, shots fired, a ba...
  [209/707] call_295_0.wav... Done: Can you get an ambulance in a cop? Get the over to 59 Alderw...
  [210/707] call_296_0.wav... Done: Hi, the gentleman was just talking to me about someone who's...
  [211/707] call_297_0.wav... Done: But, hurry up, this is the bivy. It happened. This is the bi...
  [212/707] call_298_0.wav... Done: But we went to the quails unlimited dinner last night and th...
  [213/707] call_299_0.wav... Done: Get empty over here. Come under in shot 1220. Call the grab ...

  Call_ID        Filename                                         Transcript
0    C001  call_100_0.wav                                      one different
1    C002  call_101_0.wav  This is the Blocopia Bank in 1302 with the Tra...
2    C003  call_102_0.wav                Yeah? Yeah. Yeah. Yeah. Yeah. Yeah.
3    C004  call_103_0.wav  Yes, we're at the Nelson building and there's ...
4    C005  call_104_0.wav  Listen, we're playing really bad at this. Okay...
5    C006  call_104_1.wav                                                ...
6    C007  call_105_0.wav  I'm locking in the field and I'm looking for a...
7    C008  call_106_0.wav                                Marg massacre deBen
8    C009  call_106_1.wav  They'll remember to come out, and the others f...
9    C010  call_106_2.wav  Okay, it's out for the study. Down there in th...

In [6]:
# =============================================
# CELL 5: Entity & Keyword Extraction with spaCy
# =============================================

# Define incident-related keyword categories
INCIDENT_KEYWORDS = {
    "fire": ["fire", "flame", "smoke", "burning", "blaze", "arson", "gas leak", "explosion", "exploded"],
    "accident": ["accident", "crash", "collision", "hit", "injured", "vehicle", "car", "wreck", "derail", "plane", "helicopter"],
    "theft": ["theft", "robbery", "robbed", "robbing", "stole", "stolen", "broke in", "burglar", "break-in", "breaking in", "kidnap"],
    "assault": ["fight", "assault", "attack", "knife", "weapon", "punch", "stabbing", "stabbed", "shot", "shooting", "gunshot", "gun", "killed", "murder", "homicide", "dead body", "strangled", "beat"],
    "medical": ["medical", "heart attack", "unconscious", "bleeding", "ambulance", "overdose", "not breathing", "choking", "drowning", "seizure", "CPR", "passed out", "pills"],
    "disturbance": ["disturbance", "noise", "drunk", "yelling", "suspicious", "trespassing", "harassing", "naked"]
}

def extract_incident_type(text):
    """Classify the incident type based on keywords."""
    text_lower = text.lower()
    scores = {}
    for incident_type, keywords in INCIDENT_KEYWORDS.items():
        score = sum(1 for kw in keywords if kw in text_lower)
        if score > 0:
            scores[incident_type] = score
    if scores:
        return max(scores, key=scores.get).title()
    return "Unknown"

def extract_entities(text):
    """Extract named entities using spaCy."""
    doc = nlp(text)
    locations = [ent.text for ent in doc.ents if ent.label_ in ["GPE", "LOC", "FAC"]]
    persons = [ent.text for ent in doc.ents if ent.label_ == "PERSON"]
    orgs = [ent.text for ent in doc.ents if ent.label_ == "ORG"]
    return {
        "locations": locations,
        "persons": persons,
        "organizations": orgs
    }

def extract_location_from_text(text):
    """Extract location mentions including street names."""
    entities = extract_entities(text)
    locations = entities["locations"]

    # Also look for common street patterns
    import re
    street_patterns = re.findall(
        r'(?:on|at|near|outside)\s+([A-Z][a-z]+(?:\s+(?:Street|St|Avenue|Ave|Road|Rd|Drive|Dr|Boulevard|Blvd|Lane|Ln))?(?:\s+(?:and|&)\s+[A-Z][a-z]+(?:\s+(?:Street|St|Avenue|Ave|Road|Rd))?)?)',
        text
    )
    all_locations = list(set(locations + street_patterns))
    return ", ".join(all_locations) if all_locations else "Unknown"

# Apply extraction
df_transcripts["Extracted_Event"] = df_transcripts["Transcript"].apply(extract_incident_type)
df_transcripts["Location"] = df_transcripts["Transcript"].apply(extract_location_from_text)

print("Extracted events and locations:")
df_transcripts[["Call_ID", "Extracted_Event", "Location"]]

Extracted events and locations:

    Call_ID Extracted_Event Location
0      C001         Unknown  Unknown
1      C002         Unknown  Unknown
2      C003         Unknown  Unknown
3      C004         Unknown  Unknown
4      C005         Unknown  Unknown
..      ...             ...      ...
698    C703         Unknown  Unknown
699    C704         Unknown  Unknown
700    C705         Unknown  Unknown
701    C706         Assault  Unknown
702    C707         Unknown  Unknown

[703 rows x 3 columns]

In [7]:
# =============================================
# CELL 6: Sentiment & Urgency Analysis
# =============================================

URGENCY_KEYWORDS = {
    "high": ["immediately", "hurry", "emergency", "trapped", "dying", "bleeding", "help", "quickly", "now", "knife", "gun", "weapon", "shot", "shooting", "killed", "murder", "dead", "fire", "stabbed", "not breathing", "please", "robbery", "choking", "scared"],
    "medium": ["injured", "accident", "fight", "stolen", "broke", "damage", "crash", "suspicious", "drunk", "missing", "unconscious"],
    "low": ["noise", "smell", "minor", "someone", "report", "concern"]
}

def analyze_sentiment(text):
    """Analyze sentiment using HuggingFace transformer."""
    try:
        result = sentiment_analyzer(text[:512])[0]  # Truncate for model limit
        label = result["label"]
        score = result["score"]
        # Map: NEGATIVE with high confidence = Distressed
        if label == "NEGATIVE" and score > 0.8:
            return "Distressed"
        elif label == "NEGATIVE":
            return "Concerned"
        else:
            return "Calm"
    except:
        return "Unknown"
def analyze_sentiment_with_override(text):
    """Sentiment with keyword override for obvious emergencies."""
    base = analyze_sentiment(text)
    text_lower = text.lower()
    distress_words = ["shot", "killed", "murder", "dead", "fire", "stabbed", "trapped", "robbery", "shooting", "not breathing", "help me", "please hurry"]
    if any(w in text_lower for w in distress_words) and base == "Calm":
        return "Distressed"
    return base

def calculate_urgency(text):
    """Calculate urgency score (0-1) based on keywords and patterns."""
    text_lower = text.lower()
    score = 0
    max_score = 10

    # High urgency keywords
    for kw in URGENCY_KEYWORDS["high"]:
        if kw in text_lower:
            score += 3
    # Medium urgency keywords
    for kw in URGENCY_KEYWORDS["medium"]:
        if kw in text_lower:
            score += 2
    # Low urgency keywords
    for kw in URGENCY_KEYWORDS["low"]:
        if kw in text_lower:
            score += 1

    # Exclamation marks and capitalization
    score += text.count("!") * 0.5
    score += sum(1 for word in text.split() if word.isupper() and len(word) > 1) * 0.5

    return round(min(score / max_score, 1.0), 2)

# Apply sentiment and urgency analysis
df_transcripts["Sentiment"] = df_transcripts["Transcript"].apply(analyze_sentiment_with_override)
df_transcripts["Urgency_Score"] = df_transcripts["Transcript"].apply(calculate_urgency)

print("Sentiment & Urgency Analysis:")
df_transcripts[["Call_ID", "Sentiment", "Urgency_Score"]]

Sentiment & Urgency Analysis:

    Call_ID   Sentiment  Urgency_Score
0      C001        Calm           0.00
1      C002  Distressed           0.00
2      C003        Calm           0.00
3      C004        Calm           0.00
4      C005  Distressed           0.00
..      ...         ...            ...
698    C703        Calm           0.65
699    C704  Distressed           0.00
700    C705        Calm           0.00
701    C706  Distressed           0.30
702    C707  Distressed           0.00

[703 rows x 3 columns]

In [8]:
# =============================================
# CELL 7: Generate Final Structured CSV
# =============================================

# Select and order final columns
output_cols = ["Call_ID", "Transcript", "Extracted_Event", "Location", "Sentiment", "Urgency_Score"]
df_audio_output = df_transcripts[output_cols].copy()

# Save to CSV
os.makedirs("outputs", exist_ok=True)
df_audio_output.to_csv("outputs/audio_analyst_output.csv", index=False)

print("=" * 70)
print("AUDIO ANALYST - FINAL OUTPUT")
print("=" * 70)
print(f"Total calls processed: {len(df_audio_output)}")
print(f"Output saved to: outputs/audio_analyst_output.csv")
print("=" * 70)
df_audio_output

======================================================================
AUDIO ANALYST - FINAL OUTPUT
======================================================================
Total calls processed: 703
Output saved to: outputs/audio_analyst_output.csv
======================================================================

,Call_ID,Transcript,Extracted_Event,Location,Sentiment,Urgency_Score
0,C001,one different,Unknown,Unknown,Calm,0.00
1,C002,This is the Blocopia Bank in 1302 with the Tra...,Unknown,Unknown,Distressed,0.00
2,C003,Yeah? Yeah. Yeah. Yeah. Yeah. Yeah.,Unknown,Unknown,Calm,0.00
3,C004,"Yes, we're at the Nelson building and there's ...",Unknown,Unknown,Calm,0.00
4,C005,"Listen, we're playing really bad at this. Okay...",Unknown,Unknown,Distressed,0.00
...,...,...,...,...,...,...
698,C703,Now that is vac and sample the floor. So that ...,Unknown,Unknown,Calm,0.65
699,C704,"Oh, my mind's at the doctor. You're not at the...",Unknown,Unknown,Distressed,0.00
700,C705,I'm attracted to companies. I'm no different c...,Unknown,Unknown,Calm,0.00
701,C706,"Oh, there's a student. Who's been shot, man?",Assault,Unknown,Distressed,0.30
702,C707,"Yes, I need a police officer over here. What's...",Unknown,Unknown,Distressed,0.00

### ✅ Audio Analyst Complete!
**Output:** `outputs/audio_analyst_output.csv`

| Column | Description |
|--------|-------------|
| Call_ID | Unique identifier for each call |
| Transcript | Full transcribed text |
| Extracted_Event | Classified incident type |
| Location | Extracted location mentions |
| Sentiment | Calm / Concerned / Distressed |
| Urgency_Score | 0.0 - 1.0 urgency rating |